### ISSUE TITLE
Remake theme for new Discord client. 

### ISSUE THREAD

**Issue by conifer-dev** [rose-pine/discord#2]
Not sure whats going on really, but I think it needs a little update? I've imported the theme, but it clearly does not match the preview provided, I feel like an update to discord could've been the reason?
![Screenshot from 2021-09-16 21-27-04](https://user-images.githubusercontent.com/64596327/133681457-4e5be993-a9af-4b3e-a824-9e7ba1256a2d.png)

**Comment by mvllow** [comment]
Thanks for the report! Maybe @ThatOneCalculator could chime in?

**Comment by ThatOneCalculator** [comment]
Oh yea this ***definitely*** needs an update. This was made pre-client-rewrite lol

**Comment by ThatOneCalculator** [comment]
Done!
