### ISSUE TITLE
New Discord font overrides the custom one

### ISSUE THREAD

**Issue by ArrowAced** [rose-pine/discord#8]
The custom font used in this theme gets overridden by Discord's new font, see if there's a way to fix

**Comment by mpy9** [comment]
Yea rly sad about this, hoping you guys can come up with a solution

**Comment by mvllow** [comment]
I believe the font just needs applied to the body with `!important` and possibly elsewhere. Pull requests are welcome :)

**Comment by itendtostare** [comment]
I created a pull request for this :)

**Comment by dhimanAdhikari** [comment]
Sorry for the bump but after Vencord 97ce410 update, the font isn't working (defaulting to Times New Roman or something).
I'm using the direct raw css link

Not really sure if I should report here or Vencord issues but just thought I'd let you know regardless.

**Comment by itendtostare** [comment]
what is not working :(

**Comment by mvllow** [comment]
Is this still broken after merging https://github.com/rose-pine/discord/pull/16

**Comment by dhimanAdhikari** [comment]
Its working now thanks!
